services:

  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    #environment:
    #  - APP_ENV=production
    #  - APP_DEBUG=false
    ports:
      - "8081:8081"
    volumes:
      - .:/app

  appstream:
    build:
      context: .
      dockerfile: ./stream/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - app
    volumes:
      - .:/stream
